<html>
    <head>
        <title>제목</title>
        <style></style>
    </head>
    <body>
        <h1>git</h1>
        <ul>
            <li>저장소</li>
            <li>버전</li>
        </ul>
    </body>
</html>